name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: glimmeringlight/NIS3368_JobRecruitment
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: git config --global --add safe.directory /github/workspace && git checkout docs && npm install && npm run build
        BUILD_DIR: docs/.vuepress/dist